# Netlify config file

[build]
  base = "frontend"              # 👈 Needed because Vite project is inside /frontend
  command = "npm run build"
  publish = "dist"               # 👈 relative to 'base' directory

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
